// <auto-generated />
using System;
using ClinicaMedicala.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaMedicala.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512191818_AddActivPeResursa")]
    partial class AddActivPeResursa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaMedicala.Models.Autentificare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresaIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Succes")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("Autentificari");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Consultatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosticICD10")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FisaMedicalaId")
                        .HasColumnType("int");

                    b.Property<int>("MedicId")
                        .HasColumnType("int");

                    b.Property<string>("ObservatiiMedic")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ProgramareId")
                        .HasColumnType("int");

                    b.Property<string>("SimptomePrezentate")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TratamentRecomandat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FisaMedicalaId");

                    b.HasIndex("MedicId");

                    b.HasIndex("ProgramareId")
                        .IsUnique()
                        .HasFilter("[ProgramareId] IS NOT NULL");

                    b.ToTable("Consultatii");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.DocumentMedical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaleFisier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DataIncarcare")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MedicId")
                        .HasColumnType("int");

                    b.Property<string>("Observatii")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PacientId")
                        .HasColumnType("int");

                    b.Property<int>("TipDocument")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicId");

                    b.HasIndex("PacientId");

                    b.ToTable("DocumenteMedicale");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.FisaMedicala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AntecedenteFamiliale")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrupaDeRisc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IstoricBoliCronice")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PacientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacientId")
                        .IsUnique();

                    b.ToTable("FiseMedicale");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Programare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsistentId")
                        .HasColumnType("int");

                    b.Property<int?>("CanalNotificare")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicId")
                        .HasColumnType("int");

                    b.Property<string>("MotivAnulare")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivVizita")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("NotificareTrimisa")
                        .HasColumnType("bit");

                    b.Property<int>("PacientId")
                        .HasColumnType("int");

                    b.Property<int?>("ResursaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipProgramare")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsistentId");

                    b.HasIndex("MedicId");

                    b.HasIndex("PacientId");

                    b.HasIndex("ResursaId");

                    b.ToTable("Programari");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentariu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicId")
                        .HasColumnType("int");

                    b.Property<bool>("Moderat")
                        .HasColumnType("bit");

                    b.Property<int>("PacientId")
                        .HasColumnType("int");

                    b.Property<int>("Scor")
                        .HasColumnType("int");

                    b.Property<bool>("Vizibil")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MedicId");

                    b.HasIndex("PacientId", "MedicId")
                        .IsUnique();

                    b.ToTable("Ratinguri");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Resursa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activ")
                        .HasColumnType("bit");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataScadentaRevizie")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaRevizie")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Locatie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumarInventar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stare")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("Denumire")
                        .IsUnique();

                    b.HasIndex("NumarInventar")
                        .IsUnique();

                    b.ToTable("Resurse");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Specializare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activ")
                        .HasColumnType("bit");

                    b.Property<string>("Descriere")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nume")
                        .IsUnique();

                    b.ToTable("Specializari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activ = true,
                            Nume = "Medicină de familie"
                        },
                        new
                        {
                            Id = 2,
                            Activ = true,
                            Nume = "Medicină internă"
                        },
                        new
                        {
                            Id = 3,
                            Activ = true,
                            Nume = "Cardiologie"
                        },
                        new
                        {
                            Id = 4,
                            Activ = true,
                            Nume = "Pediatrie"
                        },
                        new
                        {
                            Id = 5,
                            Activ = true,
                            Nume = "Chirurgie generală"
                        },
                        new
                        {
                            Id = 6,
                            Activ = true,
                            Nume = "Ortopedie și traumatologie"
                        },
                        new
                        {
                            Id = 7,
                            Activ = true,
                            Nume = "Obstetrică-Ginecologie"
                        },
                        new
                        {
                            Id = 8,
                            Activ = true,
                            Nume = "Neurologie"
                        },
                        new
                        {
                            Id = 9,
                            Activ = true,
                            Nume = "Dermatologie"
                        },
                        new
                        {
                            Id = 10,
                            Activ = true,
                            Nume = "Oftalmologie"
                        },
                        new
                        {
                            Id = 11,
                            Activ = true,
                            Nume = "ORL"
                        },
                        new
                        {
                            Id = 12,
                            Activ = true,
                            Nume = "Stomatologie"
                        },
                        new
                        {
                            Id = 13,
                            Activ = true,
                            Nume = "Endocrinologie"
                        },
                        new
                        {
                            Id = 14,
                            Activ = true,
                            Nume = "Psihiatrie"
                        },
                        new
                        {
                            Id = 15,
                            Activ = true,
                            Nume = "Radiologie imagistică"
                        });
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DataCreareCont")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<bool>("StatusCont")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilizatori");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MedicAsistenti", b =>
                {
                    b.Property<int>("AsistentiId")
                        .HasColumnType("int");

                    b.Property<int>("MediciId")
                        .HasColumnType("int");

                    b.HasKey("AsistentiId", "MediciId");

                    b.HasIndex("MediciId");

                    b.ToTable("MedicAsistenti");
                });

            modelBuilder.Entity("MedicPacienti", b =>
                {
                    b.Property<int>("MediciId")
                        .HasColumnType("int");

                    b.Property<int>("PacientiId")
                        .HasColumnType("int");

                    b.HasKey("MediciId", "PacientiId");

                    b.HasIndex("PacientiId");

                    b.ToTable("MedicPacienti");
                });

            modelBuilder.Entity("ResursaSpecializare", b =>
                {
                    b.Property<int>("ResurseId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializariId")
                        .HasColumnType("int");

                    b.HasKey("ResurseId", "SpecializariId");

                    b.HasIndex("SpecializariId");

                    b.ToTable("ResursaSpecializare", (string)null);
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Administrator", b =>
                {
                    b.HasBaseType("ClinicaMedicala.Models.Utilizator");

                    b.ToTable("Administratori");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Asistent", b =>
                {
                    b.HasBaseType("ClinicaMedicala.Models.Utilizator");

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tura")
                        .HasColumnType("int");

                    b.ToTable("Asistenti");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Medic", b =>
                {
                    b.HasBaseType("ClinicaMedicala.Models.Utilizator");

                    b.Property<string>("CodParafa")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal>("CostConsultatie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GradProfesional")
                        .HasColumnType("int");

                    b.Property<string>("NumarContractCAS")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specializare")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("CodParafa")
                        .IsUnique()
                        .HasFilter("[CodParafa] IS NOT NULL");

                    b.ToTable("Medici");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Pacient", b =>
                {
                    b.HasBaseType("ClinicaMedicala.Models.Utilizator");

                    b.Property<string>("AlergiiCunoscute")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AsiguratCNAS")
                        .HasColumnType("bit");

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ContactUrgentaNume")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactUrgentaTelefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("DataNastere")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupaSanguina")
                        .HasColumnType("int");

                    b.HasIndex("CNP")
                        .IsUnique()
                        .HasFilter("[CNP] IS NOT NULL");

                    b.ToTable("Pacienti");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Autentificare", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Consultatie", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.FisaMedicala", "FisaMedicala")
                        .WithMany("Consultatii")
                        .HasForeignKey("FisaMedicalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Medic", "Medic")
                        .WithMany("Consultatii")
                        .HasForeignKey("MedicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Programare", "Programare")
                        .WithOne("Consultatie")
                        .HasForeignKey("ClinicaMedicala.Models.Consultatie", "ProgramareId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FisaMedicala");

                    b.Navigation("Medic");

                    b.Navigation("Programare");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.DocumentMedical", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Medic", "Medic")
                        .WithMany("DocumenteIncarcate")
                        .HasForeignKey("MedicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicaMedicala.Models.Pacient", "Pacient")
                        .WithMany("DocumenteMedicale")
                        .HasForeignKey("PacientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medic");

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.FisaMedicala", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Pacient", "Pacient")
                        .WithOne("FisaMedicala")
                        .HasForeignKey("ClinicaMedicala.Models.FisaMedicala", "PacientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Programare", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Asistent", "Asistent")
                        .WithMany("ProgramariGestionate")
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicaMedicala.Models.Medic", "Medic")
                        .WithMany("Programari")
                        .HasForeignKey("MedicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Pacient", "Pacient")
                        .WithMany("Programari")
                        .HasForeignKey("PacientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Resursa", "Resursa")
                        .WithMany("Programari")
                        .HasForeignKey("ResursaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asistent");

                    b.Navigation("Medic");

                    b.Navigation("Pacient");

                    b.Navigation("Resursa");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Rating", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Medic", "Medic")
                        .WithMany("Ratinguri")
                        .HasForeignKey("MedicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Pacient", "Pacient")
                        .WithMany("Ratinguri")
                        .HasForeignKey("PacientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medic");

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Resursa", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Administrator", "Administrator")
                        .WithMany("ResurseAdministrate")
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("MedicAsistenti", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Asistent", null)
                        .WithMany()
                        .HasForeignKey("AsistentiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Medic", null)
                        .WithMany()
                        .HasForeignKey("MediciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicPacienti", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Medic", null)
                        .WithMany()
                        .HasForeignKey("MediciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Pacient", null)
                        .WithMany()
                        .HasForeignKey("PacientiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ResursaSpecializare", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Resursa", null)
                        .WithMany()
                        .HasForeignKey("ResurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Specializare", null)
                        .WithMany()
                        .HasForeignKey("SpecializariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Administrator", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Utilizator", null)
                        .WithOne()
                        .HasForeignKey("ClinicaMedicala.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Asistent", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Utilizator", null)
                        .WithOne()
                        .HasForeignKey("ClinicaMedicala.Models.Asistent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Medic", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Utilizator", null)
                        .WithOne()
                        .HasForeignKey("ClinicaMedicala.Models.Medic", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Pacient", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Utilizator", null)
                        .WithOne()
                        .HasForeignKey("ClinicaMedicala.Models.Pacient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaMedicala.Models.FisaMedicala", b =>
                {
                    b.Navigation("Consultatii");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Programare", b =>
                {
                    b.Navigation("Consultatie");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Resursa", b =>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Administrator", b =>
                {
                    b.Navigation("ResurseAdministrate");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Asistent", b =>
                {
                    b.Navigation("ProgramariGestionate");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Medic", b =>
                {
                    b.Navigation("Consultatii");

                    b.Navigation("DocumenteIncarcate");

                    b.Navigation("Programari");

                    b.Navigation("Ratinguri");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Pacient", b =>
                {
                    b.Navigation("DocumenteMedicale");

                    b.Navigation("FisaMedicala");

                    b.Navigation("Programari");

                    b.Navigation("Ratinguri");
                });
#pragma warning restore 612, 618
        }
    }
}
