// <auto-generated />
using System;
using ClinicaMedicala.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaMedicala.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260510163441_IitialCreate")]
    partial class IitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaMedicala.Models.Consultatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosticICD10")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FisaMedicalaId")
                        .HasColumnType("int");

                    b.Property<int>("MedicId")
                        .HasColumnType("int");

                    b.Property<string>("ObservatiiMedic")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SimptomePrezentate")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TratamentRecomandat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FisaMedicalaId");

                    b.HasIndex("MedicId");

                    b.ToTable("Consultatii");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.DocumentMedical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaleFisier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DataIncarcare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observatii")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PacientId")
                        .HasColumnType("int");

                    b.Property<int>("TipDocument")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacientId");

                    b.ToTable("DocumenteMedicale");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.FisaMedicala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AntecedenteFamiliale")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GrupaDeRisc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IstoricBoliCronice")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PacientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacientId")
                        .IsUnique();

                    b.ToTable("FiseMedicale");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Programare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicId")
                        .HasColumnType("int");

                    b.Property<string>("MotivVizita")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PacientId")
                        .HasColumnType("int");

                    b.Property<int?>("ResursaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipProgramare")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicId");

                    b.HasIndex("PacientId");

                    b.HasIndex("ResursaId");

                    b.ToTable("Programari");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Resursa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataScadentaRevizie")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaRevizie")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumarInventar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stare")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("NumarInventar")
                        .IsUnique();

                    b.ToTable("Resurse");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DataCreareCont")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<bool>("StatusCont")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilizatori");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Utilizator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Asistent", b =>
                {
                    b.HasBaseType("ClinicaMedicala.Models.Utilizator");

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tura")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Asistent");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Medic", b =>
                {
                    b.HasBaseType("ClinicaMedicala.Models.Utilizator");

                    b.Property<string>("CodParafa")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal>("CostConsultatie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GradProfesional")
                        .HasColumnType("int");

                    b.Property<string>("Specializare")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("CodParafa")
                        .IsUnique()
                        .HasFilter("[CodParafa] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Medic");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Pacient", b =>
                {
                    b.HasBaseType("ClinicaMedicala.Models.Utilizator");

                    b.Property<string>("AlergiiCunoscute")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AsiguratCNAS")
                        .HasColumnType("bit");

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ContactUrgentaNume")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactUrgentaTelefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("DataNastere")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupaSanguina")
                        .HasColumnType("int");

                    b.HasIndex("CNP")
                        .IsUnique()
                        .HasFilter("[CNP] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Pacient");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Consultatie", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.FisaMedicala", "FisaMedicala")
                        .WithMany("Consultatii")
                        .HasForeignKey("FisaMedicalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Medic", "Medic")
                        .WithMany("Consultatii")
                        .HasForeignKey("MedicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FisaMedicala");

                    b.Navigation("Medic");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.DocumentMedical", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Pacient", "Pacient")
                        .WithMany("DocumenteMedicale")
                        .HasForeignKey("PacientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.FisaMedicala", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Pacient", "Pacient")
                        .WithOne("FisaMedicala")
                        .HasForeignKey("ClinicaMedicala.Models.FisaMedicala", "PacientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Programare", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Medic", "Medic")
                        .WithMany("Programari")
                        .HasForeignKey("MedicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Pacient", "Pacient")
                        .WithMany("Programari")
                        .HasForeignKey("PacientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMedicala.Models.Resursa", "Resursa")
                        .WithMany("Programari")
                        .HasForeignKey("ResursaId");

                    b.Navigation("Medic");

                    b.Navigation("Pacient");

                    b.Navigation("Resursa");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Resursa", b =>
                {
                    b.HasOne("ClinicaMedicala.Models.Utilizator", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.FisaMedicala", b =>
                {
                    b.Navigation("Consultatii");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Resursa", b =>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Medic", b =>
                {
                    b.Navigation("Consultatii");

                    b.Navigation("Programari");
                });

            modelBuilder.Entity("ClinicaMedicala.Models.Pacient", b =>
                {
                    b.Navigation("DocumenteMedicale");

                    b.Navigation("FisaMedicala");

                    b.Navigation("Programari");
                });
#pragma warning restore 612, 618
        }
    }
}
